--- #YAML:1.0
module_name: Sort-Flat
dist_version_from: lib/Sort/Flat.pm
installdirs: site
requires:
    Filter::Simple: 0 
distribution_type: module
license: perl
dist_abstract: Case-insensitive sort
